config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'about#index', as: 'home'
  get 'portfolio', to: 'posts#index', as: 'portfolio'
  get 'download_resume', to: 'about#download_resume'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

    def index

    end

    def download_resume
        send_file "#{Rails.root}/app/assets/docs/PramodGobburi_Resume.pdf", type: "application/pdf", x_sendfile: true
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index

    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/index.html.erb
<%= stylesheet_link_tag "background_image.css" %>
<style>
    #text {
        font-size: 19px;
    }
    .lead {
        font-size: 25px;
    }
    .grid { 
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        grid-gap: 10px;
        align-items: center;
        justify-items: center;
    }
    .grid img {
        max-width: 100%;
    }

    .carousel {
        margin: 1.5rem;
    }
    .carousel-inner {
        height: auto;
    }

    .carousel-control {
        position: absolute;
        top: 1%; /* pushes the icon in the middle of the height */
        z-index: 5;
        display: inline-block;
    }

    .carousel-control-prev-icon {
        outline: #373193;
        position: absolute;
        margin-left: -20px;
        top: 130px;
    }
    .carousel-control-next-icon {
        outline: #373193;
        position: absolute;
        margin-right: -30px;
        top: 130px;
    }

    .carousel-control-next-icon:after
    {
    content: '>';
    font-size: 25px;
    color: #373193;
    }

    .carousel-control-prev-icon:after {
    content: '<';
    font-size: 25px;
    color: #373193;
    }

    .carousel-indicators li {
        background-color: gray;   
    }
    .carousel-indicators .active {
        background-color: #373193;
    }

    .primay-button:visited {
        background-color: #5371fb;
    }
    .resume-button:visited {
        color: white;
    }
    
</style>

<div class="jumbotron jumbotron-halfheight bg-growth bg-dark text-white mb-0 radius-0 jumbotron-bg-image">
  <div class="container">
    <div class="row">
        <div class="col-xl-10">
            <h5 class="display-3 text-light display-fix">Pramod Gobburi</h5>
            <div class="typewriter">
                <h6 class="lead">Software Developer</h6>
                <p id="text">Lake Charles, LA</p>
            </div>
            <div class="mt-4">
                <a href="https://www.linkedin.com/in/pramod-gobburi/"
                    class="btn btn-primary btn-lg primary-button" target="_blank">
                    <span>LinkedIn</span>
                </a>
                <a href="https://www.github.com/pramodgobburi3"
                    class="btn btn-primary btn-lg primary-button" target="_blank">
                    <span>GitHub</span>
                </a>
                <%= link_to "PDF Resume", download_resume_path, data: { turbolinks: false }, class:"btn btn-active btn-outline-light resume-button btn-hover-text-dark btn-lg ml-5" %>
            </div>
        </div>
    
      </div>
    </div>
  </div>
</div>

<div class="container py-4 px-5 mt-3 shadow bg-white">
  <h2>About Me:</h2>
  <p id="text" class="ml-3 mb-3">I am an undergraduate from McNeese State University seeking full time opportunities in Software Development fields.  
  I am experienced and knowledgeable in technical problem solving, programming, and am always driven to learn new things.</p>
  
</div>
<div>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="false">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="container py-4 my-3 shadow bg-white">
                <h3>Education:</h3>
                <br>
                <div class="container px-40">
                    <div class="card text-center px-10">
                        <div class="card-header">
                            Aug 2015 - May 2019
                        </div>
                        <div class="card-body">
                            <%= image_tag  "msu_logo.png", size:"60x50", class:"mb-3" %>
                            <h4 class="card-title">McNeese State University</h4>
                            <p id="text" class="card-text">Bachelor's of Computer Science</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="container py-4 my-3 shadow bg-white">
                <h3>Experience:</h3>
                <div class="container px-40">
                    <div class="card text-center px-10">
                        <div class="card-header">
                            Nov 2017 - Current
                        </div>
                        <div class="card-body">
                            <%= image_tag  "freelance.png", size:"100x100", class:"mb-3" %>
                            <h4 class="card-title">Freelance Development</h4>
                            <h5 id="text" class="card-text">Software Developer</h5>
                            <div style="text-align:left; margin-left:10%; margin-right:10%">
                                <ul>
                                    <li id="text" class="card-text">Led a development team, coordinated and developed multiple projects, and ensured product deployment.</li>
                                    <li id="text" class="card-text">Designed, developed and published Android applications.</li>
                                    <li id="text" class="card-text">Built various software components for a self-order kiosk and a mobile app.</li>
                                    <li id="text" class="card-text">Developed REST APIs and full stack web applications using Django framework.</li>
                                    <li id="text" class="card-text">Developed responsive web applications and dashboards using Angular.</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="container py-4 my-3 shadow bg-white">
                <h3>Skills / Languages:</h3>

                <ul class="list-group" style="margin-left: 2%; margin-right: 2%">
                    <li id="text" class="list-group-item">C, C#, Java, Python, and SQL</li>
                    <li id="text" class="list-group-item">HTML, CSS, and Javascript</li>
                    <li id="text" class="list-group-item">Full Stack Frameworks - Django, Spring Boot, Rails</li>
                    <li id="text" class="list-group-item">Mobile Development - Android, React Native</li>
                    <li id="text" class="list-group-item">Database Management - MySQL, PostgreSQL</li>
                </ul>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev" >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    </div>
</div>
<p></p>

<div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= favicon_link_tag asset_path('favicon.png') %>
    <title>Pramod Gobburi - Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= javascript_include_tag "pace.js" %>
    <%= stylesheet_link_tag "pace.css" %>
    <%= stylesheet_link_tag "bootstrap4-growth.min.css" %>
    
  </head>

 

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" style="padding-left: 15px">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-nav">
          <a class="pl-md-0 p-3 mr-5 text-light"><%= image_tag("pramod_icon.png", :size => '250x50') %></a>
      </div>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <h5><%= link_to "About Me", home_path, class:"pl-md-0 p-4 mr-4 text-light" %></h5>
          <h5><%= link_to "Portfolio", portfolio_path, class:"pl-md-0 p-4 mr-4 text-light" %></h5>
        </div>
      </div>
    </nav>

    <main role="main" style="padding-top: 70px"> 
      <%= yield %>
    </main>
  </body>
  <footer class="text-muted" style="padding-top: 50px;">
      <div class="container">
        <p class="float-right">
          <a href="">Back to top</a>
        </p>
        <p>Download a PDF Resume <%= link_to "here", download_resume_path, data: { turbolinks: false } %></p>

        <p>© 2019 Pramod Gobburi. All rights reserved. </p>
      </div>
    </footer>
</html>

app/views/posts/index.html.erb
<style>
    .layer {
        background-color: rgba(248, 247, 216, 0.7);
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }
    .display-4{
        color:#181818;
    }
    .lead {
        color: #181818;
    }
    .my-4 {
        border-color:white;
    }
    .p {
        color:#181818;
    }
    .lead {
        color:#181818;
    }
    .subtext {
        color:#181818;
    }

</style>

<div class="container">
    <h1 class="mb-5 mt-5">My Projects:</h1>
    <%
=begin%>
 <div class="mt-3 shadow bg-white mx-5">
        <div class="row align-items-center no-gutters mb-4 mb-lg-3">
            <div class="col-xl-7 col-lg-8">
                <%= image_tag("360fuel_image.jpg", class:"img-fluid mb-3 mb-lg-0", :size => '600x500') %>
            </div>
            <div class="col-xl-3 col-lg-4 mx-5">
                <div class="featured-text text-center text-lg-left">
                    <h4 class="display-5">360 Fuel App</h4>
                    <h6>Developed for 360Fuel Corp</h6>
                    <h6 class="lead">A driver app for fueling offering directions to nearby locations, user preferences, and rewards programs.</h6>
                    <p class="text-black-50 mb-0">Devloped for Android using Django framework, uses Google Maps API, Facebook API, and Mapbox API</p>
                    <p class="lead">
                        <a class="btn btn-med btn-outline-dark btn-hover-text-light btn-lg my-2" role="button" href="https://play.google.com/store/apps/details?id=net.a360fuel.gaspumptv" target="_blank">Learn more</a>
                    </p>
                </div>
            </div>
        </div>
    </div> 
<%
=end%>
<div class="mt-3 shadow bg-white mx-5">
        <div class="row align-items-center no-gutters mb-4 mb-lg-3">
            <div class="col-xl-7 col-lg-8">
                <%= image_tag("invoice_manager.png", class:"img-fluid mb-3 mb-lg-0", :size => '600x500') %>
            </div>
            <div class="col-xl-3 col-lg-4 mx-5">
                <div class="featured-text text-center text-lg-left">
                    <h4 class="display-5">Invoice Manager (In-development)</h4>
                    <h6 class="lead">An online dashboard that allows business owners to create invoices, assign invoices to clients, and manage invoices, and use analytics to track expenditures.</h6>
                    <p class="text-black-50 mb-4">Devloped using Django.</p>
                    <p class="lead">
                        <a class="btn btn-med btn-outline-dark btn-hover-text-light btn-lg my-2" role="button" href="https://github.com/pramodgobburi3/Invoice-Manager" target="_blank">Learn more</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-3 shadow bg-white mx-5">
        <div class="row align-items-center no-gutters mb-4 mb-lg-3">
            <div class="col-xl-7 col-lg-8">
                <%= image_tag("android_cdn.png", class:"img-fluid mb-3 mb-lg-0", :size => '600x500') %>
            </div>
            <div class="col-xl-3 col-lg-4 mx-5">
                <div class="featured-text text-center text-lg-left">
                    <h4 class="display-5">Android CDN (In-development)</h4>
                    <h6 class="lead">A simple drag and drop CDN that downloads any uploaded content onto an android device instantly.</h6>
                    <p class="text-black-50 mb-4">Devloped for Android using Django framework, uses background services.</p>
                    <p class="lead">
                        <a class="btn btn-med btn-outline-dark btn-hover-text-light btn-lg my-2" role="button" href="https://github.com/pramodgobburi3/Android-CDN" target="_blank">Learn more</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-3 shadow bg-white mx-5">
        <div class="row align-items-center no-gutters mb-4 mb-lg-3">
            <div class="col-xl-7 col-lg-8">
                <%= image_tag("instore.png", class:"img-fluid mb-3 mb-lg-0", :size => '600x500') %>
            </div>
            <div class="col-xl-3 col-lg-4 mx-5">
                <div class="featured-text text-center text-lg-left">
                    <h4 class="display-5">In-store Kiosk</h4>
                    <h6 class="lead">An unattended in-store kiosk for efficient ordering of products and running transactions in a convenience store.</h6>
                    <p class="text-black-50 mb-4">Devloped for Android using Django framework</p>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-3 shadow bg-white mx-5">
        <div class="row align-items-center no-gutters mb-4 mb-lg-3">
            <div class="col-xl-7 col-lg-8">
                <%= image_tag("freespeech_image.jpg", class:"img-fluid mb-3 mb-lg-0", :size => '600x500') %>
            </div>
            <div class="col-xl-3 col-lg-4 mx-5">
                <div class="featured-text text-center text-lg-left">
                    <h4 class="display-5">Free Speech Messenger</h4>
                    <h6 class="lead">An instant messaging and VOIP calling mobile application</h6>
                    <p class="text-black-50 mb-0">Devloped for Android using Google's Firebase services and Sinch SDK for VOIP calling.</p>
                    <p class="lead">
                        <a class="btn btn-med btn-outline-dark btn-hover-text-light btn-lg my-2" role="button" href="https://github.com/pramodgobburi3/Freespeech-Messenger" target="_blank">Learn more</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-3 shadow bg-white mx-5">
        <div class="row align-items-center no-gutters mb-4 mb-lg-3">
            <div class="col-xl-7 col-lg-8">
                <%= image_tag("opencv.png", class:"img-fluid mb-3 mb-lg-0", :size => '600x500') %>
            </div>
            <div class="col-xl-3 col-lg-4 mx-5">
                <div class="featured-text text-center text-lg-left">
                    <h4 class="display-5">Fun with OpenCV</h4>
                    <h6 class="lead">A collection of personal and experimental opencv projects.</h6>
                    <p class="text-black-50 mb-0">Devloped in python</p>
                    <p class="lead">
                        <a class="btn btn-med btn-outline-dark btn-hover-text-light btn-lg my-2" role="button" href="https://github.com/pramodgobburi3/OpenCV-Projects" target="_blank">Learn more</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-3 shadow bg-white mx-5">
        <div class="row align-items-center no-gutters mb-4 mb-lg-3">
            <div class="col-xl-7 col-lg-8">
                <%= image_tag("blog_image.jpg", class:"img-fluid mb-3 mb-lg-0", :size => '600x500') %>
            </div>
            <div class="col-xl-3 col-lg-4 mx-5">
                <div class="featured-text text-center text-lg-left">
                    <h4 class="display-5">Blog Application</h4>
                    <h6 class="lead">A simple blog application allowing users to create, interact and comment on posts.</h6>
                    <p class="text-black-50 mb-0">Devloped using Ruby on Rails, using PostgreSQL database</p>
                    <p class="lead">
                        <a class="btn btn-med btn-outline-dark btn-hover-text-light btn-lg my-2" role="button" href="https://github.com/pramodgobburi3/Rails-Blog" target="_blank">Learn more</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    
</div>